CC = wg++
CFLAGS = -fno-elide-constructors -std=c++11


Top_1_Tsk_12_clean : Top_1_Tsk_12_clean.o
	$(CC) $(CFLAGS) -o a Top_1_Tsk_12_clean.o

Top_1_Tsk_12_clean.o : Top_1_Tsk_12_clean.cpp Top_1_Tsk_12_clean.h
	$(CC) $(CFLAGS) -c Top_1_Tsk_12_clean.cpp
